---
- set_fact:
    vault_hcl_data: "{{ lookup('template', 'vault_hcl.j2') }}"

- debug: var=vault_hcl_data

- name: create a configmap
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ vault_configmap_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
      data:
        "vault.hcl": "{{ vault_hcl_data }}"
