---
- name: Create vault service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          app: vault
          vault_cluster: example
        name: example
        namespace: default
      spec:
        ports:
        - name: vault-client
          port: 8200
          protocol: TCP
          targetPort: 8200
        - name: vault-cluster
          port: 8201
          protocol: TCP
          targetPort: 8201
        - name: prometheus
          port: 9102
          protocol: TCP
          targetPort: 9102
        selector:
          app: vault
          vault_cluster: example
        type: ClusterIP
