- hosts: localhost
  tasks:
  - debug: msg="Running Vault Ansible Operator Playbook"
  - import_role:
      name: "get_status"
  - import_role:
      name: "tls_certs"
    when: (secrets_lookup|length==0)
  - import_role:
      name: "deploy_etcd"
    when: (etcd_cr_lookup|length==0)
  - import_role:
      name: "deploy_vault"
  - debug: msg="vault_replica_size - {{ vault_replica_size }}"

